version: '3.7'
networks:
  ladf-net:
    driver: bridge
services:
  backend:
    container_name: lafs-api
    build: lafs-api
    restart: always
    ports:
      - "3000:3000"
    links:
      - mongo
    environment:
      - DB_HOST=mongo
      - DB_NAME=lafs-db
    networks:
      - ladf-net

  mongo:
    container_name: lafs-db
    image: mongo:4
    ports:
      - "27017:27017"
    networks:
      - ladf-net

  frontend:
    container_name: lafs-web
    build: lafs
    restart: always
    ports:
      - "4200:4200"
    command: 
      bash -c "ng serve --host 0.0.0.0 --port 4200"
    networks:
      - ladf-net